# SIGNALS
signals = dict(
    CONNECTION_INITIALIZATION = 1,
    ACKNOWLEDGEMENT = 2,
)
header = dict(
    MAX_ADDRESSING_SIZE = 1500,
    MAX_ADDRESSING_SIZE_WITHOUT_HEADER = 1456,
    HEADER_SIZE = 14,
)